const form = document.getElementsById('form')
const password1El  = document.getElementById('password1')
const passwordTwo = document.getElementById('password')
const message = document.getElementById('message')
const button = document.getElementsByTagName('button')